# Generated by Django 4.2.6 on 2023-11-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Principal', 'Principal')], max_length=50)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoCientifica',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('nome_do_curso', models.CharField(max_length=255)),
                ('nome_orientador', models.CharField(max_length=255)),
                ('link_arquivo', models.URLField()),
                ('autores', models.ManyToManyField(to='producao_cientifica.autor')),
            ],
        ),
    ]
