# Generated by Django 4.2.6 on 2023-11-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao_cientifica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
