# Generated by Django 4.2.6 on 2023-11-16 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao_cientifica', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producaocientifica',
            name='data_da_defesa',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='producaocientifica',
            name='palavras_chave',
            field=models.ManyToManyField(to='producao_cientifica.palavrachave'),
        ),
    ]
