# Generated by Django 4.2.6 on 2023-12-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao_cientifica', '0003_palavrachave_producaocientifica_data_da_defesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producaocientifica',
            name='PalavrasChave',
            field=models.TextField(default='[]'),
        ),
    ]
