# Generated by Django 4.2.6 on 2023-11-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_userprofile_age_userprofile_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='usuarios\\static\\perfil.png', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
